FROM python:3.12-slim

WORKDIR /app

# Afhankelijkheden installeren
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Applicatiecode kopiëren
COPY . .

# Entrypoint uitvoerbaar maken
RUN chmod +x app/entrypoint.sh

EXPOSE 8000

ENTRYPOINT ["sh", "app/entrypoint.sh"]
